name: "Publish to Docker"
description: "Build a container image and Pushes it to Docker registry"

inputs:
  image_name:
    description: "Name of the image to push"
    required: true
  tag: 
    description: "How to tag the image. Default: latest"    
  build_args:
    description: "args used to build the docker image"
    required: false
  context: 
    description: "context path for the docker image"
    required: false
    default: "."
  token: 
    description: "token used to authenticate to GCP"
    required: true
runs:
  using: "composite"
  steps:    
      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1

      - name: Login to the Registry
        uses: docker/login-action@v1
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ inputs.token }}   #### must use the atypon_checkout action before this action
      
      - name: Set the tag
        shell: bash
        run: |
          if [ -z "${{inputs.tag}}" ]
          then
            echo "final_tag=latest" >> $GITHUB_ENV
          else
            echo "final_tag=${{inputs.tag}}" >> $GITHUB_ENV
          fi
      
      - name: Build and Push the Image
        uses: docker/build-push-action@v2
        with:
          context: ${{inputs.context}} 
          push: true
          build-args: ${{inputs.build_args}}                
          tags: us-central1-docker.pkg.dev/${{inputs.image_name}}:${{env.final_tag}}
